# Generated by Django 6.0.3 on 2026-09-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_name_alter_patient_urgency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+254712345678', max_length=20),
        ),
    ]
