# Generated by Django 6.0.3 on 2026-09-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reservation_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reservation_date', models.DateTimeField()),
                ('pickup_window', models.CharField(max_length=100)),
                ('pickup_location', models.JSONField(default=list)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='patients.patient')),
            ],
        ),
    ]
