# Generated by Django 6.0.3 on 2026-09-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
