# Generated by Django 6.0.3 on 2026-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_expiry_date_medicalrecord_record_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('GENERAL', 'General Health'), ('BLOOD_WORK', 'Detailed Blood Analysis'), ('HLA_TYPING', 'HLA Tissue Typing'), ('CROSSMATCH', 'Crossmatch Test')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
