# Generated by Django 6.0.3 on 2026-09-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_expiry_date_medicalrecord_record_type_and_more'),
        ('patients', '0003_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('GENERAL', 'General Health'), ('BLOOD_WORK', 'Detailed Blood Analysis'), ('HLA_TYPING', 'HLA Tissue Typing'), ('CROSSMATCH', 'Crossmatch Test')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
